name: Build Resume PDF

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: docker://pandoc/extra
        with:
          args: >-
            --pdf-engine=lualatex
            resume.md 
            -o Luis_Fernando_Dresch_Resume.pdf

      - name: Upload Resume PDF
        uses: actions/upload-artifact@v4
        with:
          name: Luis_Fernando_Dresch_Resume.pdf
          path: Luis_Fernando_Dresch_Resume.pdf

